Match points
TimonRey/PingPongApp pull request #15
Opened 2017-12-01 13:41 UTC by TimonRey

The ping pong app is now able to show the match points of each player. 
Also the new hasSomeOneOfThePlayersTwoPointsMore method can find out, if the point difference between player one and player two is 2. In this case the set will be over and the game after 2 won sets of a player too.
The new updateScoreOfPlayer method (we will rename this) is able to change the match points and to reset the whole game, if the game is over.

2017-12-01 13:52 UTC, PhilippSpo requested changes

2017-12-01 13:52 UTC, PhilippSpo commented on src/main/java/Game.java
> +    public boolean hasSomeoneOfThePlayersElevenPointsYet() {
We still have to rename this one.

2017-12-01 13:52 UTC, PhilippSpo commented on src/main/java/GameMonitor.java
> +             if (spiel.hasSomeoneOfThePlayersElevenPointsYet()) {
The code here from line 17 to 19 is exactly the same as line 23 to 25. As we spoke about earlier we should avoid such duplication #DRY

2017-12-01 13:52 UTC, PhilippSpo commented on src/main/java/Players.java
> +    public int howManyMatchPointsDoWeHave(Players player1, Players player2) {
Do we need this one?

2017-12-01 16:13 UTC, emmenko submitted a review, later dismissed
I left some comments, let's discuss this in person how we should proceed here 😉

2017-12-01 16:13 UTC, emmenko commented on src/main/java/Game.java
> +    public boolean hasThePlayerTwoWon() {
Since those two methods are identical, we should probably have one method which accepts a `player` as an argument.

2017-12-01 16:13 UTC, emmenko commented on src/main/java/GameMonitor.java
> +    Game spiel;
This should be renamed to `game` (english)

2017-12-01 16:13 UTC, emmenko commented on src/main/java/Players.java
> +    int matchPoints;
What do you need this for? I think a `player` should only "care" about their points.

Although now that I think about it, this is also not quite "correct". A `player` should contain information about the person, I'm not sure it makes much sense to keep the points in here, because points belong to a `game`.
We can talk again about this, just wanted to bring this up.

2017-12-01 16:13 UTC, emmenko commented on src/main/java/Main.java
> +}
I think we can remove this class

2017-12-01 16:13 UTC, emmenko commented on src/main/java/PingPong.java
> +        public MyHandler (GameMonitor irgendeinname) {
`irgendeinname` --> `monitor`

Also `MyHandler` --> `PingPongServer`

2017-12-01 16:13 UTC, emmenko commented on src/main/java/GameMonitor.java
> +        System.out.println(String.format("%s:%s", firstPlayer.getMatchPoints(), secondPlayer.getMatchPoints()));
Nitpick: the log output should probably be extracted into a different method

2017-12-01 16:13 UTC, emmenko commented on src/main/java/GameMonitor.java
> +        this.spiel = new Game(firstPlayer, secondPlayer);
As we discussed last time, this should be a `match`.

Maybe to make it more clear (in regards to e.g. tennis):
* a `match` consists of `sets` and `games`
  * a `match` is won when a player wins the majority of `sets` (e.g. 2 out of 3, 3 out of 5, 5 out of 7)
* a `set` consists of `games`
  * in tennis you need to win 6 `games` to win a `set`
* a `game` consists of points
  * in tennis this means 4 points: `15, 30, 40, win`

<img width="655" alt="image" src="https://user-images.githubusercontent.com/1110551/33491151-a468b8b6-d6b9-11e7-8cd3-1b3cdb7765c6.png">

Now, in our case it's enough to have `match` and `games`. A `game` consists of 11 points. You have to win 2 games to win a match.

2017-12-18 16:02 UTC, PhilippSpo commented on src/main/java/Main.java
> +}
@TimonRey should we remove the class? I don't see any other issues apart from this.

2017-12-18 16:10 UTC, TimonRey commented on src/main/java/Main.java
> +}
@PhilippSpo yes, we can remove the class

2017-12-18 16:19 UTC, PhilippSpo approved these changes

2017-12-18 16:19 UTC, merged